sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Wjy23603@


  alioss:
    access-key-secret:
    endpoint:
    access-key-id:
    bucket-name:
  redis:
    host:localhost
    port:6379
